Task.create([
    {name: "食べ物を残さない", image: "/img/tabemono.png"},
    {name: "水筒(マイボトル)を使う", image: "/img/bottle.png"},
    {name: "部屋を出るとき電気を消す", image: "/img/denki.png"},
    {name: "冷暖房の温度設定を意識する", image: "/img/reidanbou.png"},
    {name: "お昼は部屋の電気を消す", image: "/img/hirudenki.png"},
    {name: "シャワーを浴びるとき水をこまめに止めるようにする", image: "/img/shower.png"},
    {name: "ティッシュを無駄遣いしない", image: "/img/tissue.png"},
    {name: "エコバックを使う", image: "/img/ecobag.png"},
    {name: "フェアトレード商品のものを買う(明治のザ・チョコレート)", image: "/img/fairtrade.png"},
    {name: "地域の食材を購入する", image: "/img/tiiki.png"},
    {name: "寄付付き商品を買う", image: "/img/kihu.png"}, 
    {name: "訳あり商品を買う", image: "/img/wakeari.png"},
    {name: "詰め替えの商品を買う", image: "/img/tumekae.png"},
    {name: "包装が少ない商品を買う", image: "/img/housou.png"},
    {name: "ヴィーガン料理を食べてみる", image: "/img/vegan.png"},
    {name: "料理をするとき賞味期限が近い商品から使う", image: "/img/kigen.png"},
    {name: "駅まで自転車や徒歩で移動する", image: "/img/toho.png"},
    {name: "使わない服を寄付する", image: "/img/huku.png"},
    {name: "SDGs関連の投稿にいいねやリツイートなど拡散する", image: "/img/retweet.png"},
    {name: "SDGsについて調べてみる", image: "/img/siraberu.png"}
    ])

Category.create([
    {name: "goaltitle", image: "/img/goaltitle"},
    {name: "goal1", image:  "/img/goal1.png"},
    {name: "goal2", image:  "/img/goal2.png"},
    {name: "goal3", image: "/img/goal3.png"},
    {name: "goal4", image:  "/img/goal4.png"},
    {name: "goal5", image: "/img/goal5.png"},
    {name: "goal6", image: "/img/goal6.png"},
    {name: "goal7", image: "/img/goal7.png"},
    {name: "goal8", image: "/img/goal8.png"},
    {name: "goal9", image: "/img/goal9.png"},
    {name: "goal10", image: "/img/goal10.png"},
    {name: "goal11", image: "/img/goal11.png"},
    {name: "goal12", image: "/img/goal12.png"},
    {name: "goal13", image: "/img/goal13.png"},
    {name: "goal14", image: "/img/goal14.png"},
    {name: "goal15", image: "/img/goal15.png"},
    {name: "goal16", image: "/img/goal16.png"},
    {name: "goal17", image: "/img/goal17.png"},
    {name: "goal18", image: "/img/goal18.png"}
    
    ])